/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as CiRouteImport } from './routes/ci'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as EngageRouteImport } from './routes/engage'
import { Route as GhRouteImport } from './routes/gh'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RequestProposalRouteImport } from './routes/request-proposal'
import { Route as RfpRouteImport } from './routes/rfp'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademyBespokeRouteImport } from './routes/academy.bespoke'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as CareersSlugRouteImport } from './routes/careers.$slug'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as ExpertiseIndexRouteImport } from './routes/expertise.index'
import { Route as ExpertiseSlugRouteImport } from './routes/expertise.$slug'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as PeopleIndexRouteImport } from './routes/people.index'
import { Route as PeopleSlugRouteImport } from './routes/people.$slug'
import { Route as TrainingIndexRouteImport } from './routes/training.index'
import { Route as TrainingCorporateRouteImport } from './routes/training.corporate'
import { Route as AcademyProgrammesIndexRouteImport } from './routes/academy.programmes.index'
import { Route as AcademyProgrammesSlugRouteImport } from './routes/academy.programmes.$slug'
import { Route as TrainingProgrammesIndexRouteImport } from './routes/training.programmes.index'
import { Route as TrainingProgrammesSlugRouteImport } from './routes/training.programmes.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const CiRoute = CiRouteImport.update({
  id: '/ci',
  path: '/ci',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EngageRoute = EngageRouteImport.update({
  id: '/engage',
  path: '/engage',
  getParentRoute: () => rootRouteImport,
} as any)
const GhRoute = GhRouteImport.update({
  id: '/gh',
  path: '/gh',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestProposalRoute = RequestProposalRouteImport.update({
  id: '/request-proposal',
  path: '/request-proposal',
  getParentRoute: () => rootRouteImport,
} as any)
const RfpRoute = RfpRouteImport.update({
  id: '/rfp',
  path: '/rfp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyBespokeRoute = AcademyBespokeRouteImport.update({
  id: '/academy/bespoke',
  path: '/academy/bespoke',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersSlugRoute = CareersSlugRouteImport.update({
  id: '/careers/$slug',
  path: '/careers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseIndexRoute = ExpertiseIndexRouteImport.update({
  id: '/expertise/',
  path: '/expertise/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertiseSlugRoute = ExpertiseSlugRouteImport.update({
  id: '/expertise/$slug',
  path: '/expertise/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleSlugRoute = PeopleSlugRouteImport.update({
  id: '/people/$slug',
  path: '/people/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingCorporateRoute = TrainingCorporateRouteImport.update({
  id: '/training/corporate',
  path: '/training/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyProgrammesIndexRoute = AcademyProgrammesIndexRouteImport.update({
  id: '/academy/programmes/',
  path: '/academy/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyProgrammesSlugRoute = AcademyProgrammesSlugRouteImport.update({
  id: '/academy/programmes/$slug',
  path: '/academy/programmes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingProgrammesIndexRoute = TrainingProgrammesIndexRouteImport.update({
  id: '/training/programmes/',
  path: '/training/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingProgrammesSlugRoute = TrainingProgrammesSlugRouteImport.update({
  id: '/training/programmes/$slug',
  path: '/training/programmes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/ci': typeof CiRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/engage': typeof EngageRoute
  '/gh': typeof GhRoute
  '/locations': typeof LocationsRoute
  '/privacy': typeof PrivacyRoute
  '/request-proposal': typeof RequestProposalRoute
  '/rfp': typeof RfpRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/academy/bespoke': typeof AcademyBespokeRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/expertise/$slug': typeof ExpertiseSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/training/corporate': typeof TrainingCorporateRoute
  '/academy/': typeof AcademyIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/expertise/': typeof ExpertiseIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/academy/programmes/$slug': typeof AcademyProgrammesSlugRoute
  '/training/programmes/$slug': typeof TrainingProgrammesSlugRoute
  '/academy/programmes/': typeof AcademyProgrammesIndexRoute
  '/training/programmes/': typeof TrainingProgrammesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/ci': typeof CiRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/engage': typeof EngageRoute
  '/gh': typeof GhRoute
  '/locations': typeof LocationsRoute
  '/privacy': typeof PrivacyRoute
  '/request-proposal': typeof RequestProposalRoute
  '/rfp': typeof RfpRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/academy/bespoke': typeof AcademyBespokeRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/expertise/$slug': typeof ExpertiseSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/training/corporate': typeof TrainingCorporateRoute
  '/academy': typeof AcademyIndexRoute
  '/careers': typeof CareersIndexRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/expertise': typeof ExpertiseIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/people': typeof PeopleIndexRoute
  '/training': typeof TrainingIndexRoute
  '/academy/programmes/$slug': typeof AcademyProgrammesSlugRoute
  '/training/programmes/$slug': typeof TrainingProgrammesSlugRoute
  '/academy/programmes': typeof AcademyProgrammesIndexRoute
  '/training/programmes': typeof TrainingProgrammesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/ci': typeof CiRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/engage': typeof EngageRoute
  '/gh': typeof GhRoute
  '/locations': typeof LocationsRoute
  '/privacy': typeof PrivacyRoute
  '/request-proposal': typeof RequestProposalRoute
  '/rfp': typeof RfpRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/academy/bespoke': typeof AcademyBespokeRoute
  '/careers/$slug': typeof CareersSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/expertise/$slug': typeof ExpertiseSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/people/$slug': typeof PeopleSlugRoute
  '/training/corporate': typeof TrainingCorporateRoute
  '/academy/': typeof AcademyIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/expertise/': typeof ExpertiseIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/training/': typeof TrainingIndexRoute
  '/academy/programmes/$slug': typeof AcademyProgrammesSlugRoute
  '/training/programmes/$slug': typeof TrainingProgrammesSlugRoute
  '/academy/programmes/': typeof AcademyProgrammesIndexRoute
  '/training/programmes/': typeof TrainingProgrammesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/ci'
    | '/contact'
    | '/cookie-policy'
    | '/engage'
    | '/gh'
    | '/locations'
    | '/privacy'
    | '/request-proposal'
    | '/rfp'
    | '/sitemap'
    | '/terms'
    | '/academy/bespoke'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/expertise/$slug'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/people/$slug'
    | '/training/corporate'
    | '/academy/'
    | '/careers/'
    | '/case-studies/'
    | '/expertise/'
    | '/industries/'
    | '/insights/'
    | '/people/'
    | '/training/'
    | '/academy/programmes/$slug'
    | '/training/programmes/$slug'
    | '/academy/programmes/'
    | '/training/programmes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/ci'
    | '/contact'
    | '/cookie-policy'
    | '/engage'
    | '/gh'
    | '/locations'
    | '/privacy'
    | '/request-proposal'
    | '/rfp'
    | '/sitemap'
    | '/terms'
    | '/academy/bespoke'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/expertise/$slug'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/people/$slug'
    | '/training/corporate'
    | '/academy'
    | '/careers'
    | '/case-studies'
    | '/expertise'
    | '/industries'
    | '/insights'
    | '/people'
    | '/training'
    | '/academy/programmes/$slug'
    | '/training/programmes/$slug'
    | '/academy/programmes'
    | '/training/programmes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/ci'
    | '/contact'
    | '/cookie-policy'
    | '/engage'
    | '/gh'
    | '/locations'
    | '/privacy'
    | '/request-proposal'
    | '/rfp'
    | '/sitemap'
    | '/terms'
    | '/academy/bespoke'
    | '/careers/$slug'
    | '/case-studies/$slug'
    | '/expertise/$slug'
    | '/industries/$slug'
    | '/insights/$slug'
    | '/people/$slug'
    | '/training/corporate'
    | '/academy/'
    | '/careers/'
    | '/case-studies/'
    | '/expertise/'
    | '/industries/'
    | '/insights/'
    | '/people/'
    | '/training/'
    | '/academy/programmes/$slug'
    | '/training/programmes/$slug'
    | '/academy/programmes/'
    | '/training/programmes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CiRoute: typeof CiRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  EngageRoute: typeof EngageRoute
  GhRoute: typeof GhRoute
  LocationsRoute: typeof LocationsRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestProposalRoute: typeof RequestProposalRoute
  RfpRoute: typeof RfpRoute
  SitemapRoute: typeof SitemapRoute
  TermsRoute: typeof TermsRoute
  AcademyBespokeRoute: typeof AcademyBespokeRoute
  CareersSlugRoute: typeof CareersSlugRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  ExpertiseSlugRoute: typeof ExpertiseSlugRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  PeopleSlugRoute: typeof PeopleSlugRoute
  TrainingCorporateRoute: typeof TrainingCorporateRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  ExpertiseIndexRoute: typeof ExpertiseIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
  AcademyProgrammesSlugRoute: typeof AcademyProgrammesSlugRoute
  TrainingProgrammesSlugRoute: typeof TrainingProgrammesSlugRoute
  AcademyProgrammesIndexRoute: typeof AcademyProgrammesIndexRoute
  TrainingProgrammesIndexRoute: typeof TrainingProgrammesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ci': {
      id: '/ci'
      path: '/ci'
      fullPath: '/ci'
      preLoaderRoute: typeof CiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engage': {
      id: '/engage'
      path: '/engage'
      fullPath: '/engage'
      preLoaderRoute: typeof EngageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gh': {
      id: '/gh'
      path: '/gh'
      fullPath: '/gh'
      preLoaderRoute: typeof GhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-proposal': {
      id: '/request-proposal'
      path: '/request-proposal'
      fullPath: '/request-proposal'
      preLoaderRoute: typeof RequestProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfp': {
      id: '/rfp'
      path: '/rfp'
      fullPath: '/rfp'
      preLoaderRoute: typeof RfpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/bespoke': {
      id: '/academy/bespoke'
      path: '/academy/bespoke'
      fullPath: '/academy/bespoke'
      preLoaderRoute: typeof AcademyBespokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/$slug': {
      id: '/careers/$slug'
      path: '/careers/$slug'
      fullPath: '/careers/$slug'
      preLoaderRoute: typeof CareersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise/': {
      id: '/expertise/'
      path: '/expertise'
      fullPath: '/expertise/'
      preLoaderRoute: typeof ExpertiseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertise/$slug': {
      id: '/expertise/$slug'
      path: '/expertise/$slug'
      fullPath: '/expertise/$slug'
      preLoaderRoute: typeof ExpertiseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$slug': {
      id: '/people/$slug'
      path: '/people/$slug'
      fullPath: '/people/$slug'
      preLoaderRoute: typeof PeopleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/corporate': {
      id: '/training/corporate'
      path: '/training/corporate'
      fullPath: '/training/corporate'
      preLoaderRoute: typeof TrainingCorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/programmes/': {
      id: '/academy/programmes/'
      path: '/academy/programmes'
      fullPath: '/academy/programmes/'
      preLoaderRoute: typeof AcademyProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/programmes/$slug': {
      id: '/academy/programmes/$slug'
      path: '/academy/programmes/$slug'
      fullPath: '/academy/programmes/$slug'
      preLoaderRoute: typeof AcademyProgrammesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/programmes/': {
      id: '/training/programmes/'
      path: '/training/programmes'
      fullPath: '/training/programmes/'
      preLoaderRoute: typeof TrainingProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/programmes/$slug': {
      id: '/training/programmes/$slug'
      path: '/training/programmes/$slug'
      fullPath: '/training/programmes/$slug'
      preLoaderRoute: typeof TrainingProgrammesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  CiRoute: CiRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  EngageRoute: EngageRoute,
  GhRoute: GhRoute,
  LocationsRoute: LocationsRoute,
  PrivacyRoute: PrivacyRoute,
  RequestProposalRoute: RequestProposalRoute,
  RfpRoute: RfpRoute,
  SitemapRoute: SitemapRoute,
  TermsRoute: TermsRoute,
  AcademyBespokeRoute: AcademyBespokeRoute,
  CareersSlugRoute: CareersSlugRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  ExpertiseSlugRoute: ExpertiseSlugRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  PeopleSlugRoute: PeopleSlugRoute,
  TrainingCorporateRoute: TrainingCorporateRoute,
  AcademyIndexRoute: AcademyIndexRoute,
  CareersIndexRoute: CareersIndexRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  ExpertiseIndexRoute: ExpertiseIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  TrainingIndexRoute: TrainingIndexRoute,
  AcademyProgrammesSlugRoute: AcademyProgrammesSlugRoute,
  TrainingProgrammesSlugRoute: TrainingProgrammesSlugRoute,
  AcademyProgrammesIndexRoute: AcademyProgrammesIndexRoute,
  TrainingProgrammesIndexRoute: TrainingProgrammesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
